### ISSUE TITLE
Add operator HashKey Cloud

### ISSUE THREAD

**Issue by HashKeyCloud** [symbioticfi/cosmos-sdk#10]
Name - HashKey Cloud
Short Description - HashKey Cloud, as a leading provider of global Web3 infrastructure and a core member of the HashKey Group, focuses on delivering professional, stable, and secure blockchain services to clients worldwide.
Ethereum operator address - 0x55aE254C7bDbb7C17F6B158c7FA8653FB845eC3D
Validator consensus address - 13353FD1D3B6F9CA9FE166C4EF6E35291357BB35

**Comment by alrxy** [comment]
> 0x55aE254C7bDbb7C17F6B158c7FA8653FB845eC3D

done
