### ISSUE TITLE
Add operator Simply Staking

### ISSUE THREAD

**Issue by frangrech** [symbioticfi/cosmos-sdk#11]
Name: Simply Staking
Short Description: Simply Staking runs highly reliable and secure infrastructure in our own datacentre in Malta, built with the aim of supporting the growth of the blockchain ecosystem.
Ethereum operator address: `0xa956de8c5589b033A51F25FF7811e6088b87f932`
Validator consensus address: `280CCE477EC2EB6CC3A087D01440D97542846072`

**Comment by alrxy** [comment]
done
