### ISSUE TITLE
Add operator 0xDaVinci

### ISSUE THREAD

**Issue by Jkirbo** [symbioticfi/cosmos-sdk#14]
Name - 0xDaVinci
Short Description - 0xDaVinci is company with extensive experience in the blockchain field, specializing in data analysis and support for various blockchain ecosystems.
Ethereum operator address - 0xF9Ae0389A9FD3b10045c04eaAB92655116C23321
Validator consensus address - 3ADECF7C4A3BD4746A06010A7316F7DFE4E59067

**Comment by alrxy** [comment]
done
