### ISSUE TITLE
Add `DSRV` operator

### ISSUE THREAD

**Issue by skonhwang** [symbioticfi/cosmos-sdk#16]
Name - DSRV
Short Description - DSRV is an integrated blockchain solutions company with the mission of enriching the crypto ecosystem via stronger connectivity. We strive to be your gateway to a suite of all-comprehensive blockchain services. Everything distributed, served complete.
Ethereum operator address - 0x1F110fa319Ac7E637507e006C80d426c89D1489B
Validator consensus address - 250A1F15303D5CE76E3367C74C0F0B586B339BA7

**Comment by alrxy** [comment]
done
