### ISSUE TITLE
Add operator Chorus One

### ISSUE THREAD

**Issue by kamsz** [symbioticfi/cosmos-sdk#17]
Name - Chorus One
Short Description - Chorus One is a leading staking provider, managing over 3 billion USD in assets across more than 50 networks.

Ethereum operator address - 0xB23DFB4ba57aFAf2DcfcADC45A56a4E82AD01cD0
Validator consensus address - 54A4C0A5F1FAAC7497EF237D64FCAFEF06473CCC

**Comment by alrxy** [comment]
done
