### ISSUE TITLE
Add operator Kiln

### ISSUE THREAD

**Issue by alchimestre** [symbioticfi/cosmos-sdk#18]
Name - Kiln
Short Description - Kiln is one of the largest node operators on the market with over $8.6B under management and running over 40 protocols.
Ethereum operator address - 0xC3Af4d137c1aa260C87C01f9e7e7637951245DF6
Validator consensus address - 3AA28F1C66B4184B272122CE9D23F7A033A1E34B

**Comment by alrxy** [comment]
done
