### ISSUE TITLE
Add Pier Two operator

### ISSUE THREAD

**Issue by uink45** [symbioticfi/cosmos-sdk#19]
Name - Pier Two
Short Description - Pier Two supports enterprise grade infrastructure for institutional clients specializing in non custodial staking while simultaneously building an Ethereum Light Client called Lantern.
Ethereum operator address - 0x3ca67Ad85620D15354d2358dBb538b3fCB8F9b87
Validator consensus address - A0EA56C8560DFD8A78E67CDBD86B9B34CA8B69EC

**Comment by alrxy** [comment]
done
