### ISSUE TITLE
Add 01node operator

### ISSUE THREAD

**Issue by daemon2k3** [symbioticfi/cosmos-sdk#20]
Name - 01node
Short Description - High Quality Institutional Blockchain Validation and Staking
Ethereum operator address - 0xfdB7787Cb7ed6E0A9b3e3821C5B2Ca4333A1E24b
Validator consensus address - 36D2AFCDFAB19C464D1EBD198A4565E2A525F841

**Comment by alrxy** [comment]
please register in symbiotic core contracts as in docs.symbiotic.fi

**Comment by alrxy** [comment]
> Name - 01node Short Description - High Quality Institutional Blockchain Validation and Staking Ethereum operator address - 0xfdB7787Cb7ed6E0A9b3e3821C5B2Ca4333A1E24b Validator consensus address - 36D2AFCDFAB19C464D1EBD198A4565E2A525F841

.

**Comment by daemon2k3** [comment]
I've registered here : https://holesky.etherscan.io/address/0xa02C55a6306c859517A064fb34d48DFB773A4a52
according to docs.

**Comment by alrxy** [comment]
opt-in please into network and vaults

**Comment by alrxy** [comment]
done
