### ISSUE TITLE
Add KudasaiJP operator

### ISSUE THREAD

**Issue by 43z708** [symbioticfi/cosmos-sdk#21]
Name - KudasaiJP
Short Description - KudasaiJP/Omakase is a professional staking and validation service. We also contribute to innovative projects via marketing and development support.
Ethereum operator address - 0x2b0832fe79d34835fbba618d3fb7cb29178cff37
Validator consensus address - 1C2D3D939F95CD8A4697C647FE890F738F4C89BA

**Comment by alrxy** [comment]
done
