### ISSUE TITLE
Add stakefish operator

### ISSUE THREAD

**Issue by tongson** [symbioticfi/cosmos-sdk#23]
stakefish
Description: stakefish is the leading validator in the crypto ecosystem
Ethereum Address: 0x5D92C75d897e1e17a09F73376e1740Ba9aBa9b92
Validator Address: 9D102BF8C81C99412C28C6AB14730DAE8B45B725

**Comment by alrxy** [comment]
> stakefish Description: stakefish is the leading validator in the crypto ecosystem Ethereum Address: 0x5D92C75d897e1e17a09F73376e1740Ba9aBa9b92 Validator Address: 9D102BF8C81C99412C28C6AB14730DAE8B45B725

please registerd in symbiotic contracts https://docs.symbiotic.fi/handbooks/Handbook%20for%20Operators#actions-in-symbiotic-core

**Comment by tongson** [comment]
@alrxy Registered and verified all opt-ins.

**Comment by alrxy** [comment]
done
