### ISSUE TITLE
Add InfraSingularity Operator

### ISSUE THREAD

**Issue by is-dhiren** [symbioticfi/cosmos-sdk#24]
Name - InfraSingularity
Short Description - We aim to transform the Web3 ecosystem as a pioneering Web3 Investor and builder.
Ethereum operator address - 0x4A1bb298c57D0eEFfD57d7eED0Ee86923583Fa73
Validator consensus address - CE6EFD97A8AF87133971940DD7C270E2DAB8A92E

**Comment by alrxy** [comment]
done
