### ISSUE TITLE
Add P-OPS

### ISSUE THREAD

**Issue by pops-one** [symbioticfi/cosmos-sdk#25]
**Name:** P-OPS
**Short Description:**  P-OPS TEAM is a decentralized organization providing you with validation and staking services, blockchain consultation, growth acceleration and investment capital for innovative Web 3.0 projects.
**Ethereum operator address:** 0x47069a38120D296a83FDF53b73e52d7c11Bac7bE
**Validator consensus address:** A3EBCE91C3F4D1D2194F5B78458AFFAB2786158F

**Comment by alrxy** [comment]
done
