### ISSUE TITLE
Add HinkalTest Operator

### ISSUE THREAD

**Issue by alexandr-martirosyan** [symbioticfi/cosmos-sdk#26]
Name - hinkal_test
Short Description - for testing
Ethereum operator address - 0xd4b276Fe7a06625727947d44c99b062C0C14AB55
Validator consensus address - EC1BB5D07D73DA16BB2A0D225DA1798DB1F35A56

**Comment by alrxy** [comment]
please register in symbiotic core contracts https://docs.symbiotic.fi/handbooks/Handbook%20for%20Operators/#actions-in-symbiotic-core

**Comment by alexandr-martirosyan** [comment]
already registered

**Comment by alrxy** [comment]
> already registered

opt-in please to the network

**Comment by alexandr-martirosyan** [comment]
Done. Sorry, I somehow forgot to call this function.

**Comment by alrxy** [comment]
done
