### ISSUE TITLE
Add OpsLayer 

### ISSUE THREAD

**Issue by PSjoe** [symbioticfi/cosmos-sdk#28]
Name: OpsLayer
Short Description: OpsLayer powers innovative Web3 networks with expert infrastructure management, software development, and finance operation services. https://opslayer.com
Ethereum operator address - 0x7aa64A525b90cCe46422e01f33c316fED57c5fa0
Validator consensus address - 43F7716133AF660CD29FB2988234393DB23419E4

**Comment by alrxy** [comment]
> 43F7716133AF660CD29FB2988234393DB23419E4

done
