### ISSUE TITLE
Add Finoa Consesus Services operator

### ISSUE THREAD

**Issue by puneetfinoa** [symbioticfi/cosmos-sdk#29]
Name: FCS
Short Description: Stake and grow your assets using Finoa's institutional-grade infrastructure.
Ethereum operator address: 0xa0B3243F097Db7D58A88d596379849904F813E82
Validator consensus address: 47A90FC4F9A5BEAEFFFF46827ECF958BFE2463EE

**Comment by alrxy** [comment]
please register and opt-in to symbiotic core contracts https://docs.symbiotic.fi/handbooks/Handbook%20for%20Operators/#actions-in-symbiotic-core

**Comment by puneetfinoa** [comment]
@alrxy I have already opted it, what is the next step now

**Comment by alrxy** [comment]
done
