### ISSUE TITLE
Add blockscape

### ISSUE THREAD

**Issue by BlockscapeLab** [symbioticfi/cosmos-sdk#30]
Name - blockscape
Short Description - Blockscape is a team of experienced blockchain professionals based in Switzerland, committed to promoting self-custody, decentralized finance, and trustless technology through their innovative solutions and services.
Ethereum operator address - 0x4FA15763dA2B3C07DD497462b25BcA7F85C5C651
Validator consensus address - 762558A94BF6CFBE0318DC9B91D979B163C9C8FD

**Comment by alrxy** [comment]
> Name - blockscape Short Description - Blockscape is a team of experienced blockchain professionals based in Switzerland, committed to promoting self-custody, decentralized finance, and trustless technology through their innovative solutions and services. Ethereum operator address - 0x4e3bc2318819c2244647b015b7498dc39fb0b56d8acf40c8937e92713919fb79 Validator consensus address - 762558A94BF6CFBE0318DC9B91D979B163C9C8FD

your address is too long for eth
