### ISSUE TITLE
Second validator activation webfarm3

### ISSUE THREAD

**Issue by dmsv312** [symbioticfi/cosmos-sdk#31]
You changed network, so my parameters changed. Old priv_validator_key.json file didn't work on new network. 
I already had closed issue here - https://github.com/symbioticfi/cosmos-sdk/issues/12. 
Please approve my new data, thank you. 
And where can i check new networks? Do you have a group somewhere in social networks for validators?

Name - webfarm3
Short Description - Webfarm3 is a team of professional node runners. We are part of many blockchain projects in different roles.
Ethereum operator address - 0xC68FA05fB86b60a97848e155913EfD3aAa3F87f2
Validator consensus address - 22993A4C27AF27037D8CE146B53A6CA068695B00

**Comment by dmsv312** [comment]
Also have errors with syncing, like it was in this isssue - https://github.com/symbioticfi/cosmos-sdk/issues/8.
I'm stuck at block №38650

2:50AM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash.  Expected 1AE10F55DD5886BC86EFD501FE59165488B65EC411A0637963A3D5B22FBA9B04, got 716826EF2B69F3BB6DC7820B3F234AF81BF4DCC1FBF926DF9F68A4638A0B145C. Check ABCI app for non-determinism" module=p2p peer="Peer{MConn{100.20.114.140:26656} 30a07da2029074bd48d5bf53423f8f4ebe706167 out}"

**Comment by alrxy** [comment]
> You changed network, so my parameters changed. Old priv_validator_key.json file didn't work on new network. I already had closed issue here - #12. Please approve my new data, thank you. And where can i check new networks? Do you have a group somewhere in social networks for validators?
> 
> Name - webfarm3 Short Description - Webfarm3 is a team of professional node runners. We are part of many blockchain projects in different roles. Ethereum operator address - 0xC68FA05fB86b60a97848e155913EfD3aAa3F87f2 Validator consensus address - 22993A4C27AF27037D8CE146B53A6CA068695B00

the old data was migrated to the new network, yes, there is a chat for operators, please contact our public accounts

**Comment by alrxy** [comment]
> Also have errors with syncing, like it was in this isssue - #8. I'm stuck at block №38650
> 
> 2:50AM ERR Stopping peer for error err="reactor validation error: wrong Block.Header.AppHash. Expected 1AE10F55DD5886BC86EFD501FE59165488B65EC411A0637963A3D5B22FBA9B04, got 716826EF2B69F3BB6DC7820B3F234AF81BF4DCC1FBF926DF9F68A4638A0B145C. Check ABCI app for non-determinism" module=p2p peer="Peer{MConn{100.20.114.140:26656} 30a07da2029074bd48d5bf53423f8f4ebe706167 out}"

this fill be fixed soon, check repo updates

**Comment by dmsv312** [comment]
> > You changed network, so my parameters changed. Old priv_validator_key.json file didn't work on new network. I already had closed issue here - #12. Please approve my new data, thank you. And where can i check new networks? Do you have a group somewhere in social networks for validators?
> > Name - webfarm3 Short Description - Webfarm3 is a team of professional node runners. We are part of many blockchain projects in different roles. Ethereum operator address - 0xC68FA05fB86b60a97848e155913EfD3aAa3F87f2 Validator consensus address - 22993A4C27AF27037D8CE146B53A6CA068695B00
> 
> the old data was migrated to the new network, yes, there is a chat for operators, please contact our public accounts

@alrxy I can see on website that you only have twitter. Where can i find this chat?

**Comment by alrxy** [comment]
> > > You changed network, so my parameters changed. Old priv_validator_key.json file didn't work on new network. I already had closed issue here - #12. Please approve my new data, thank you. And where can i check new networks? Do you have a group somewhere in social networks for validators?
> > > Name - webfarm3 Short Description - Webfarm3 is a team of professional node runners. We are part of many blockchain projects in different roles. Ethereum operator address - 0xC68FA05fB86b60a97848e155913EfD3aAa3F87f2 Validator consensus address - 22993A4C27AF27037D8CE146B53A6CA068695B00
> > 
> > 
> > the old data was migrated to the new network, yes, there is a chat for operators, please contact our public accounts
> 
> @alrxy I can see on website that you only have twitter. Where can i find this chat?

try here https://symbiotic.typeform.com/contact, will update your keys soon

**Comment by alrxy** [comment]
done
