### ISSUE TITLE
Add Chainflow Operator

### ISSUE THREAD

**Issue by ritvik-32** [symbioticfi/cosmos-sdk#32]
Name - Chainflow
Short Description - Independent validator building crypto infrastructure for a brighter future. Stake with us to support our mission of reinforcing blockchains with decentralization at their core.
Ethereum operator address - 0x51CF0a2D70C0C6C364a22DDDCf3EBb7d430a13DC
Validator consensus address - 6D7C4AE58CD8E06FB2B1B52DD291DE1E42E183A0

**Comment by alrxy** [comment]
> Name - Chainflow Short Description - Independent validator building crypto infrastructure for a brighter future. Stake with us to support our mission of reinforcing blockchains with decentralization at their core. Ethereum operator address - 0x51CF0a2D70C0C6C364a22DDDCf3EBb7d430a13DC Validator consensus address - 6D7C4AE58CD8E06FB2B1B52DD291DE1E42E183A0

done
