### ISSUE TITLE
Add BwareLabs

### ISSUE THREAD

**Issue by Mihaita-Catalin** [symbioticfi/cosmos-sdk#34]
Name - BwareLabs
Short Description - Guaranteed availability and up-time backed by a professional blockchain infrastructure team.
Ethereum operator address - 0x2196770EF899D297d589F07B6A93b3973190E88b
Validator consensus address - 38E7BF2C477D732896D38AA2DB770693E71F9517

**Comment by alrxy** [comment]
done
