### ISSUE TITLE
Add P2P.org

### ISSUE THREAD

**Issue by felichita** [symbioticfi/cosmos-sdk#37]
Name - P2P.org
Short Description - P2P.ORG Validator (P2P.org) - an early contributor & long-time Cosmos Ecosystem participant. Stake with us for a secure, reliable and simple service
Ethereum operator address - 0x4fBa9a587B9A36b343168dcF70061E58aEd16CCF
Validator consensus address - 77A5599C64817131243E0982072460B85AC02B63

**Comment by alrxy** [comment]
please opt-in to symbiotic core contracts https://docs.symbiotic.fi/handbooks/Handbook%20for%20Operators/#actions-in-symbiotic-core

**Comment by alrxy** [comment]
done, wait for finalization
