### ISSUE TITLE
Add Stakely.io

### ISSUE THREAD

**Issue by Josepdal** [symbioticfi/cosmos-sdk#45]
Name - Stakely.io
Short Description - Stakely, your trusted node operator and infrastructure provider, leader in staking solutions.
Ethereum operator address - 0x790062F39a2e477Ca4fA05Ba00D3bd08C5E40386
Validator consensus address - AE2690C0488467E81FB11F75F7BD08594D016EF3

**Comment by alrxy** [comment]
please opt-in to symbiotic core contracts https://docs.symbiotic.fi/handbooks/Handbook%20for%20Operators/#actions-in-symbiotic-core

**Comment by Josepdal** [comment]
> please opt-in to symbiotic core contracts https://docs.symbiotic.fi/handbooks/Handbook%20for%20Operators/#actions-in-symbiotic-core

Done!
