### ISSUE TITLE
Add Pier Two operator

### ISSUE THREAD

**Issue by uink45** [symbioticfi/cosmos-sdk#46]
Name - Pier Two
Short Description - Pier Two supports enterprise grade infrastructure for institutional clients specializing in non custodial staking while simultaneously building an Ethereum Light Client called Lantern.
Ethereum operator address - 0x3ca67Ad85620D15354d2358dBb538b3fCB8F9b87
Validator consensus address - F0CE6ABA70D88DA23E256A181EFE05F2F6E3E37B

**Comment by alrxy** [comment]
done, wait for block finalization
