### ISSUE TITLE
Add blockscape

### ISSUE THREAD

**Issue by BlockscapeLab** [symbioticfi/cosmos-sdk#47]
Name - blockscape
Short Description - Blockscape is a team of experienced blockchain professionals based in Switzerland, committed to promoting self-custody, decentralized finance, and trustless technology through their innovative solutions and services.
Ethereum operator address - 0x12Ea8924fe4c915FB64e2b412B706ADE319D9f1f
Validator consensus address - 762558A94BF6CFBE0318DC9B91D979B163C9C8FD

**Comment by alrxy** [comment]
done, wait for block finalization
