### ISSUE TITLE
Add Next Finance Tech

### ISSUE THREAD

**Issue by kajeagentspi** [symbioticfi/cosmos-sdk#48]
Name - Next Finance Tech
Short Description - Next Finance Tech, based in Japan, provides Ethereum staking services. We operate our Ethereum validators on-premises at our own Tokyo data center in Japan, using Azure as a failover option in case of system failures.
Ethereum operator address - 0x516Dc09Df83B53bD6C125C5544478eC2EB31851A
Validator consensus address - 57FDEA285DC157E0387DC63E978C8371C41A2941

**Comment by alrxy** [comment]
please registed and opt-in to symbiotic core contracts https://docs.symbiotic.fi/handbooks/Handbook%20for%20Operators/#actions-in-symbiotic-core

**Comment by kajeagentspi** [comment]
Registered!

**Comment by alrxy** [comment]
done, wait for finalization
