### ISSUE TITLE
Add deNodes

### ISSUE THREAD

**Issue by bombermine3** [symbioticfi/cosmos-sdk#52]
Name - deNodes
Short Description - deNodes, a proven staking provider, ensures fast and secure operations for PoS networks through superior performance with bare-metal machines
Ethereum operator address - 0x09505f2B29062dE4E91E0053490B8f6c3f7D29Fc
Validator consensus address - 59D85029938E7BB43F2670C8FC3D645BD918C514

**Comment by alrxy** [comment]
done, wait for block finalization
