### ISSUE TITLE
Add BlockHunters

### ISSUE THREAD

**Issue by blockhunters-dev** [symbioticfi/cosmos-sdk#53]
Name - BlockHunters 🎯
Short Description - Hunting for the best stake since 2020
Ethereum operator address - 0x70cE1546546F9BdD1860e2dA5B6984a49C3c22c8
Validator consensus address - 05FC3D764FD1288A8061E0F39E7D5E1531F80070

**Comment by alrxy** [comment]
done, wait for finalization
