### ISSUE TITLE
Add Sitnoprodex

### ISSUE THREAD

**Issue by juliesitnikoffa** [symbioticfi/cosmos-sdk#55]
Name - Sitnoprodex
Short Description - We are validators on awesome networks
Ethereum operator address - 0x09e6B2B6634c5b676198f32587De1C89C7Cd7bA1
Validator consensus address - 9019B68B9F64C79EDD6DEBF13DB5BCAED7ACB7F9

**Comment by alrxy** [comment]
done, wait for finalization
