### ISSUE TITLE
Add B-Harvest

### ISSUE THREAD

**Issue by qj0r9j0vc2** [symbioticfi/cosmos-sdk#56]
Name - B-Harvest
Short Description - Provides secure validation services for dPoS networks
Ethereum operator address - 0xb7FF9e16b40F8626b5ED758F6D1C5834C0B5aCF2
Validator consensus address - F29E488CC34D43A0FCB2E9457D054D6ED36816A7

**Comment by alrxy** [comment]
done, wait for finalization
