### ISSUE TITLE
Add QuantNode

### ISSUE THREAD

**Issue by sshamanov** [symbioticfi/cosmos-sdk#57]
Name - QuantNode
Short Description - Safe & Easy2Use Staking Provider 🌎 Supporting networks at early stage
Ethereum operator address - 0x2251Fd3080d1656f53226bEAdfD1c9f7Cb9A0104
Validator consensus address - A25856FA3DD1769AE4BE01847019EB4A6E1284DF

**Comment by alrxy** [comment]
done, wait for finalization
