### ISSUE TITLE
Add Labatechpro

### ISSUE THREAD

**Issue by labadabadapta** [symbioticfi/cosmos-sdk#58]
Name - Labatechpro
Short Description - The future is inevitable, you just need to find your place in this WEB3 world
Ethereum operator address - 0x767e67dE863C1E8E7880579e99a3C99aB1Ffb257
Validator consensus address - DAED58CA63792BE57B146662B6B269E2C3FCB218

**Comment by alrxy** [comment]
done, wait for finalization
