### ISSUE TITLE
Add GalaxyDigital

### ISSUE THREAD

**Issue by wcampbellgalaxy** [symbioticfi/cosmos-sdk#60]
Name - GalaxyDigital
Short Description - Galaxy is a digital asset and blockchain leader helping institutions, startups, and qualified individuals shape a changing economy.
Ethereum operator address - 0x767f7576944D321374921DF138589a30e3C5030d
Validator consensus address - 3991ED914A1CC9AFE9167F9B3F46D03C3C754C0A

**Comment by wcampbellgalaxy** [comment]
Registered testnet operator ✅ 

see tx: https://holesky.etherscan.io/tx/0x3ba1472f1549ad400e5470cf7e33e5423e14b75208c503a20fefdf42a5577c7b

but having trouble understanding the instructions here:

> Opt in to the example vaults using [this contract](https://holesky.etherscan.io/address/0x63E459f3E2d8F7f5E4AdBA55DE6c50CbB43dD563#writeContract):
> optIn(0xE9387B4abA8073988b462Db204af0f343F181a0d)
> optIn(0x89D62D1d89d8636367fc94998b3bE095a3d9c2f9)
> Opt in to the example stubchain network via [this contract](https://holesky.etherscan.io/address/0x973ba45986FF71742129d23C4138bb3fAd4f13A5#writeContract):
> optIn(0xDD46e5C9618540489410033A1B690744B123b41D)
> Verify all opt-ins by calling isOptedIn(operator, vault/network) using the contract above

Can you please explain in more detail? What exactly is needed here?

I need to still:
- Opt into vaults
- Opt into stubchain
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/13008785-21c4-409e-b2a6-101edef9321e">

**Comment by alrxy** [comment]
> Registered testnet operator ✅
> 
> see tx: https://holesky.etherscan.io/tx/0x3ba1472f1549ad400e5470cf7e33e5423e14b75208c503a20fefdf42a5577c7b
> 
> but having trouble understanding the instructions here:
> 
> > Opt in to the example vaults using [this contract](https://holesky.etherscan.io/address/0x63E459f3E2d8F7f5E4AdBA55DE6c50CbB43dD563#writeContract):
> > optIn(0xE9387B4abA8073988b462Db204af0f343F181a0d)
> > optIn(0x89D62D1d89d8636367fc94998b3bE095a3d9c2f9)
> > Opt in to the example stubchain network via [this contract](https://holesky.etherscan.io/address/0x973ba45986FF71742129d23C4138bb3fAd4f13A5#writeContract):
> > optIn(0xDD46e5C9618540489410033A1B690744B123b41D)
> > Verify all opt-ins by calling isOptedIn(operator, vault/network) using the contract above
> 
> Can you please explain in more detail? What exactly is needed here?
> 
> I need to still:
> 
> * Opt into vaults
> * Opt into stubchain
> 
> <img alt="image" width="1497" src="https://private-user-images.githubusercontent.com/110464691/372708519-13008785-21c4-409e-b2a6-101edef9321e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjcxNTksIm5iZiI6MTcyNzg2Njg1OSwicGF0aCI6Ii8xMTA0NjQ2OTEvMzcyNzA4NTE5LTEzMDA4Nzg1LTIxYzQtNDA5ZS1iMmE2LTEwMWVkZWY5MzIxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMTAwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2Y1Mzk3ZmI4OTdjMDkyNGVhZTI0NGEwZDE1MDM3MzZiNDZmNjUyMzhlNmI0ODkxM2ZiZWRmNjUxMmQ2ODA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x9pyhTHKvMFH_phdGTaBZgBNozRb0M3Z4N9NXuJ3ZIw">

yes, call opt-in in linked contract to given arguments as in docs from exact opeartor registered address

**Comment by wcampbellgalaxy** [comment]
Ok, i just opted into the contracts and the Stubchain, see txs:

Contracts:
- https://holesky.etherscan.io/tx/0xa18e86207987f49c0318701b4c6b8b4d1a0435c86bd395ef7865ab14c62c15ef
- https://holesky.etherscan.io/tx/0xb3528a6a7e56e6f85b48cabed0192b7ce24a0f53062dcca247b4e7e0a37695a9

Stubchain:
- https://holesky.etherscan.io/tx/0xc8bee5ffa6d53241e6b9830cdfa32b2dd4def7de013d58d22497649255876450

This PR should be ready to merge now @alrxy

**Comment by wcampbellgalaxy** [comment]
confirmed we are opted into all 3:
vault 1:
![image](https://github.com/user-attachments/assets/9da7137b-ad60-45c3-ab9b-f42f065be59b)
vault 2:
![image](https://github.com/user-attachments/assets/8567af4b-cd7b-4319-a724-51ae9b05a61c)
stubchain:
![image](https://github.com/user-attachments/assets/46195aa8-1111-4f5b-b9ce-66b1f45d3aee)

**Comment by wcampbellgalaxy** [comment]
Can you please merge this when you get a chance and ensure we are added to the active set. Thank you! @alrxy

**Comment by alrxy** [comment]
done
