### ISSUE TITLE
Add Nansen

### ISSUE THREAD

**Issue by curlycrypto184** [symbioticfi/cosmos-sdk#61]
Name - Nansen
Short Description - Nansen is a leading on-chain analytics platform founded in 2020, and is now one of the most trusted names in crypto, serving traders and institutions. Disclaimer: delegating comes with slashing risks
Ethereum operator address - 0xcE5EF56c1cB5b080711AF16BECd09Bb00202F258
Validator consensus address - E34DD7F4C0B137C3EFA68A8362F037F895527F66

**Comment by alrxy** [comment]
done, wail for finalization
