### ISSUE TITLE
Add Tane

### ISSUE THREAD

**Issue by tksohishi** [symbioticfi/cosmos-sdk#62]
Name - Tane
Short Description - Tané is a blockchain network operator, managed by a group of crypto-native product builders, backed by Japanese enterprises.
Ethereum operator address - 0x7bb11BE268088B000eD4B1b94014D40371A3a7d3
Validator consensus address - 48319443C4C75C0C2726AAC8412457702C718BA7

**Comment by alrxy** [comment]
done
