### ISSUE TITLE
Add ByteHub

### ISSUE THREAD

**Issue by sanchezbingjunior** [symbioticfi/cosmos-sdk#63]
Name - ByteHub
Short Description - An IT firm focused on DeFi development, creating secure and innovative decentralized financial solutions.
Ethereum operator address - 0xC96B05737EBBD42cE0DD3ABD0f246153c3Fee5aF
Validator consensus address - B3F2ECC668BDFAA2E44B3FBA8702C933BA66BC3A

**Comment by alrxy** [comment]
done
