### ISSUE TITLE
! Alert! Official Twitter is sending pishing website

### ISSUE THREAD

**Issue by rayrayhere** [symbioticfi/cosmos-sdk#64]
The official twitter may be stolen. It keeps sending pishing website: deposits-symbiotic.fi

Be very careful and please take quick actions!

![WechatIMG3](https://github.com/user-attachments/assets/7f2b115b-2c4c-4d9c-81ce-55b63a0b5fdf)
![sympishiing](https://github.com/user-attachments/assets/8ce5f52b-7db0-47eb-a12b-0696b50f968d)

**Comment by alrxy** [comment]
thanks a lot! resolved
