### ISSUE TITLE
Add Stakeway

### ISSUE THREAD

**Issue by rushabh101** [symbioticfi/cosmos-sdk#66]
Name - Stakeway by Gateway.fm
Short Description - Stakeway by Gateway.fm is a premier staking provider offering Enterprise Grade Infrastructure tailored for customers seeking reliable and secure staking solutions
Ethereum operator address - 0xe8355d39baF8372c7f579c0F713c3f49C17ad9BA
Validator consensus address - EC6C3625BF11F7E9E9D54E80FE1BA39F15BDBE4F

**Comment by alrxy** [comment]
done
