### ISSUE TITLE
Add Luganodes 

### ISSUE THREAD

**Issue by hakaiLuganodes** [symbioticfi/cosmos-sdk#68]
Name - Luganodes
Short Description - Luganodes is a Swiss-Operated Institutional Grade Staking Provider
Ethereum operator address - 0xF14665e7C001D720Eb92D8e9f0D82231BC07c261
Validator consensus address - 991C9BC6093E64DD0EC29EE2C1FDAC022363FC68

**Comment by alrxy** [comment]
done
