### ISSUE TITLE
Add Chainflow

### ISSUE THREAD

**Issue by cfl0ws** [symbioticfi/cosmos-sdk#69]
Name - Chainflow 
Short Description - Independent validator building crypto infrastructure for a brighter future. Stake with us to support our mission of reinforcing blockchains with decentralization at their core. 
Ethereum operator address - 0x51CF0a2D70C0C6C364a22DDDCf3EBb7d430a13DC
Validator consensus address - 00BC052C2B61CED5BFF0BA8B70018CE68952FF3A

**Comment by alrxy** [comment]
done
