### ISSUE TITLE
Add Validation Cloud

### ISSUE THREAD

**Issue by kevin-matthews-vc** [symbioticfi/cosmos-sdk#70]
Name - Validation Cloud
Short Description - Validation Cloud is a Web3 platform that delivers elite, high-performance node and staking infrastructure.
Ethereum operator address - 0x503c17171bb5B005b0ba319F4a590d1Fc0189217
Validator consensus address - C019515BA2EDC151B36094198626BAE4C9BB1741`

**Comment by alrxy** [comment]
done
