### ISSUE TITLE
Add SkyTeam

### ISSUE THREAD

**Issue by maxbitov** [symbioticfi/cosmos-sdk#72]
Name - SkyTeam
Short Description - We are a team that has accumulated extensive experience in supporting decentralized networks.
Ethereum operator address - 0x12C9D326eaF1e4BB7df38C7F5cf45f1C9018D83b
Validator consensus address - 64DE100C12D74051CCC17DDB4E661C95D94FF4C8

**Comment by alrxy** [comment]
done
