### ISSUE TITLE
Add Finoa Consensus Service Operator

### ISSUE THREAD

**Issue by timpel-fcs** [symbioticfi/cosmos-sdk#74]
Name - FCS
Short Description - Stake and grow your assets using Finoa's institutional-grade infrastructure
Ethereum operator address - 0xa0B3243F097Db7D58A88d596379849904F813E82
Validator consensus address - 47A90FC4F9A5BEAEFFFF46827ECF958BFE2463EE

**Comment by alrxy** [comment]
done
