### ISSUE TITLE
Add TodGrinder

### ISSUE THREAD

**Issue by todgrinder** [symbioticfi/cosmos-sdk#76]
Name - TodGrinder
Short Description - Solo operator with deep expertise and experience in launching and supporting validators and operators in various decentralized networks
Ethereum operator address - 0x236633d5c0Ec75C49bA3577B9CF551b552FE3E55
Validator consensus address - 27A0D7FDDA7D0010A83AA63E203E00F8660F12F8

**Comment by alrxy** [comment]
done
