### ISSUE TITLE
Add Trigon

### ISSUE THREAD

**Issue by mattjokovich** [symbioticfi/cosmos-sdk#77]
Name - Trigon
Short Description - Developer, validator and operator who supports and helps networks in the early stages of development and after their release into the WEB3.
Ethereum operator address - 0x9189f7e59756d64ca3ac9db2bcc8888a3f04c19b
Validator consensus address - 8E33EE4FE163910CB6DE9F4B011D72C9944C0BFD

**Comment by alrxy** [comment]
done
