### ISSUE TITLE
Add Vitwit

### ISSUE THREAD

**Issue by kaustubhkapatral** [symbioticfi/cosmos-sdk#79]
Name - Vitwit
Short Description - Vitwit has been at the forefront of the blockchain industry since 2017. With extensive experience and expertise, we have established ourselves as a reliable validator across more than 20 Proof-of-Stake (PoS) networks, staked assets totaling over 34 million USD.
Ethereum operator address - 0x9b54713Bf9541a6a5c4e84F53e5305d304feeCf1
Validator consensus address - 6D3EE78EED2CDC3FC35C3DC2F9E25A37C26734B3

**Comment by alrxy** [comment]
done
