### ISSUE TITLE
Add Encapsulate

### ISSUE THREAD

**Issue by aditya-manit** [symbioticfi/cosmos-sdk#80]
Name - Encapsulate
Short Description - We have been validating for about half a decade, operating across more than 40 blockchain networks and managing around a quarter of a billion in delegated stake. Some of the prominent networks we validate for include Ethereum, Sui, Mina, Celestia, Avalanche, Eigen Layer Operator, Axelar, The Graph Protocol, Chainflip, and many more. You can find the full list of supported networks on our [website](https://encapsulate.xyz)

Ethereum operator address - 0x314452C6F9Cbd580032a80Af95A48fB4E81b948c
Validator consensus address - 1B81D63978DA096C68A40768DABD007D2C294A10

**Comment by alrxy** [comment]
done

**Comment by aditya-manit** [comment]
Thanks
