### ISSUE TITLE
Add operator Everstake

### ISSUE THREAD

**Issue by oarypovskyi-everstake** [symbioticfi/cosmos-sdk#9]
Name - Everstake
Short Description - Everstake is a top-tier responsible validator trusted by 725k+ users across 75+ blockchain networks. Created by engineers for the entire community in 2018
Ethereum operator address - 0x01DB45433dbd214D386857590A255ABFe6daD0fb
Validator consensus address - B5704EF96D59F11B89EA8EE06F71EF01D7A1F33E

**Comment by alrxy** [comment]
> B5704EF96D59F11B89EA8EE06F71EF01D7A1F33E

done
